name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code à partie de mon repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Vérifier la qualité du code
      - name: Run ESLint
        run: npm run lint

      # Lancer les tests unitaires et d’intégration
      - name: Run Jest and Supertest
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm test

      # Configurer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Construire l’image Docker
      - name: Build Docker image
        run: docker build -t onlinecourse-backend .

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}